### ISSUE TITLE
Twin Reflector Proxy - Ingest twin elements

### ISSUE THREAD

**Issue by tux2323** [microsoft/azure-digital-twins-java#16]
## User Story `Ingest twin elements`

> As **Cloud Connector**,
> **I want** ingest topology (e.g. spaces) events asynchronously into ADT,
> **so that** the updates are reflected in the ADT topology
> **and** I don't have to worry about the REST management API limitations (e.g. throtteling) and the REST API details (e.g. Create or Update).

##  User Story Details

Ingest twin instances (Create or update) as event asynchronously into ADT including properties, attributes and relationships. The events are processed from Azure Event Hub and mapped into several ADT REST API calls.

The ADT REST API is defined [here](https://docs.westcentralus.azuresmartspaces.net/management/swagger/ui/index).

## Context Building Block View

![twin-reflector_building-block-view](https://user-images.githubusercontent.com/141782/59093248-c12f5780-8913-11e9-8222-bff108babf07.png)

### Pre-conditions

- The ontology must be predefined (in ADT version 1 the space types and property-keys are defined)
- ADT IoT Hub needs to be provision

### Event Hub Headers

Header | Values | Required | Description
-- | -- | -- | --
TwinReflectorProxy-MessageType | `full`, `partial`, `delete` | yes |
TwinReflectorProxy-EventTimestamp | e.g. `2018-09-20T07:35:00.8587882-07:00` | no | timestamp as UTC as ISO 8601 formatted date string that identifies the sampling time of the payload. For example, 2018-09-20T07:35:00.8587882-07:00 (**optional**)
TwinReflectorProxy-CorrelationId | | no | UUID  (**optional**)

### Send event to create or update topology element

> The create and update message contains the full state (all attributes, all properties and all relationships) of the topology element!

#### Event Hub Message

**Headers:**

- TwinReflectorProxy-MessageType: `ingest`

**Message Payload (Example):**

```javascript
{
  "id": "F3",                               // external Id
  "entity-type": "Space",
  "attributes": {
     "friendlyName": "Office"
  },
  "properties": [
      {
          "entity-type": "propertykeys",
          "name": "title",
          "value": "Office London"
      }
  ],
  "relationships": [
      {
          "entity-type":     "space",
          "name":            "parent",
          "target-id":       "C1"           // external Id of the campus
      }
  ]
}
```

#### Twin Reflector Proxy Message Processing

- Query for the topology element by the external id (via ADT REST Management API as GET)
- Apply the attributes and properties from the message (Unit of Work Pattern)
- Creates or update the element in ADT (via ADT REST Management API as POST or PATCH)
- Updates the properties of the element in ADT

#### ADT State (ADT Model V1)

```yaml
# Space
- id: "7487abd8-a5b9-acab-5fdb-7a74ac1674f5"                  # ADT ID
 - name: "C1"

- id: "5d3600bc-5475-11e9-8647-d663bd873d93"                  # ADT ID
 - name: "F3"
 - friendlyName: "Office"
 - parentId: "7487abd8-a5b9-acab-5fdb-7a74ac1674f5"           # ADT Id parent
 - properties:
    title: "Office London"
```
